#!/usr/bin/env bash
# Create RSA key pair with specified parameters

# Define the filename for the private key
private_key_file="school"

# Create RSA key pair with specified parameters
ssh-keygen -t rsa -b 4096 -N "betty" -f "$private_key_file"

